version: '3.8'

services:
  home-library:
    container_name: home-library
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - type: bind
        source: ./src
        target: /app/src
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: "${PORT}"
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public"
    env_file: 
      - .env
    depends_on:
      - postgresdb
    networks:
      - home-library-network

  postgresdb:
    container_name: postgresdb
    restart: always
    build: 
      context: ./postgres/
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    networks:
      - home-library-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "logging_collector=on"
      - "-c"
      - "log_directory=./logs"
      - "-c"
      - "log_filename=postgresql.log"
      - "-c"
      - "log_statement=all"

networks:
  home-library-network:
    driver: bridge

volumes:
  pgdata:
